-- create_ads_table.sql
CREATE TABLE IF NOT EXISTS ads (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  image_url TEXT NOT NULL,
  target_url TEXT NOT NULL,
  alt VARCHAR(255) DEFAULT NULL,
  position VARCHAR(100) DEFAULT NULL,
  active TINYINT(1) DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
